# Generated by Django 5.0.1 on 2024-03-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_app', '0002_rename_status_task_is_done_remove_task_task_catagory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
